### ISSUE TITLE
VHF FM Support

### ISSUE THREAD

**Issue by blanu** [Beartooth/codec2-ios#1]
It would be great to get support for mode 2400B for compatibility with VHF FM radios. As far as I can tell, this requires exposing not just the Codec2 codec2_encode/codec2_decode functions, but also the freedv API functions (freedv_open, freedv_tx, freedv_rx, etc.) in order to get access to the VHF FM modem implementation.

**Comment by jeffypooo** [comment]
@blanu So a swift wrapper on `freedv_api.h`? 

Simple enough. I likely won't have time to work on this until next weekend, but you're welcome to submit a PR. Otherwise, I'll plan on doing it then.

**Comment by jeffypooo** [comment]
Merged from #2.
